[package]
name = "spine-rs"
version = "0.1.0+spec-1.0.0"
description = "A spec-compliant parser for the Spine configuration language"
edition = "2024"
license = "BSD-3-Clause"
rust-version = "1.85"
repository = "https://codeberg.org/razkar/spine-rs"
categories = ["parsing", "config", "text-processing"]
keywords = ["config", "parser", "spine", "configuration", "serialization"]
readme = "README.md"

[dependencies]
farben = "0.20"
unicode-width = "0.2.2"
