[package]
name = "spine-abi"
version = "0.1.0-beta.1"
description = "C ABI bindings for spine-rs"
edition = "2024"
license = "BSD-3-Clause"
rust-version = "1.85"
repository = "https://codeberg.org/razkar/spine-rs"
categories = ["parsing", "config", "development-tools::ffi"]
keywords = ["ffi", "c-bindings", "spine", "config", "parser"]
readme = "README.md"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
spine-rs = { workspace = true }

[build-dependencies]
cbindgen = "0.29.2"
